
image: Visual Studio 2019
platform:
   - amd64


install:
   - git submodule update --init --recursive
   - nuget.exe install python -Version 3.8.0 -OutputDirectory C:\
   - nuget.exe install python -Version 3.7.0 -OutputDirectory C:\
   - nuget.exe install python -Version 3.6.0 -OutputDirectory C:\
   - C:\Python.3.8.0\tools\python.exe -m pip install pybind11_stubgen


before_build:
   - mkdir "python/rlutilities"


build_script:
   - mkdir build38
   - cd build38
   - cmake .. -G "Visual Studio 16 2019" -Ax64 -DWITH_TESTS=TRUE -DTARGET_LANGUAGE=python -DPYTHON_EXECUTABLE=C:\Python.3.8.0\tools\python.exe
   - cmake --build . --config Release
   - mv Release/rlutilities.*.pyd ../python/rlutilities
   - cd ..
   - mkdir build37
   - cd build37
   - cmake .. -G "Visual Studio 16 2019" -Ax64 -DWITH_TESTS=TRUE -DTARGET_LANGUAGE=python -DPYTHON_EXECUTABLE=C:\Python.3.7.0\tools\python.exe
   - cmake --build . --config Release
   - mv Release/rlutilities.*.pyd ../python/rlutilities
   - cd ..
   - mkdir build36
   - cd build36
   - cmake .. -G "Visual Studio 16 2019" -Ax64 -DWITH_TESTS=TRUE -DTARGET_LANGUAGE=python -DPYTHON_EXECUTABLE=C:\Python.3.6.0\tools\python.exe
   - cmake --build . --config Release
   - mv Release/rlutilities.*.pyd ../python/rlutilities
   - cd ..
   
after_build:
   - cd python/rlutilities
   - C:\Python38-x64\python.exe -m pybind11_stubgen rlutilities --no-setup -o=.. --root_module_suffix=
   - cp ../__init__.py __init__.py
   - cp ../../LICENSE.txt LICENSE.txt
   - cd ..
   - ps: Compress-Archive -Path rlutilities -DestinationPath rlutilities.zip
   
test: off

artifacts:
   - path: python/rlutilities.zip
   
deploy: off